issue#38#39 Add Social Login from Google and Facebook
ashdaily/turbocommerce pull request #57
Opened 2021-03-30 19:42 UTC by Jerry-1947

I just leave console.log(user) for the reference of the response from social login

2021-04-04 00:15 UTC, ashdaily requested changes
Looks fine, just small changes.

2021-04-04 00:15 UTC, ashdaily commented on frontend/src/google.svg
> +</svg>
this file should be inside `public` folder

2021-04-04 00:15 UTC, ashdaily commented on frontend/src/pages/Login.js
> +						}}
move it to scss file

2021-04-04 00:15 UTC, ashdaily commented on frontend/src/pages/Login.js
> +						<span style={{ background: "#fff", padding: '0 5px' }}>OR</span>
move it to scss file

2021-04-04 00:15 UTC, ashdaily commented on frontend/src/pages/Login.js
> +						<span style={{ background: "#fff", padding: '0 5px' }}>OR</span>
why not just wrap span in a p tag and use `text-center` 🤔

2021-04-04 17:39 UTC, Jerry-1947 commented on frontend/src/pages/Login.js
> +						<span style={{ background: "#fff", padding: '0 5px' }}>OR</span>
To add through line

2021-04-06 13:41 UTC, ashdaily approved these changes

2021-04-06 13:42 UTC, merged