issue#40 Add Wishlist Remove Wishlist Empty Wishlist Login Wishlist
ashdaily/turbocommerce pull request #67
Opened 2021-04-03 09:47 UTC by Jerry-1947

Also, Change the Product Listing page content according to the New Products API

2021-04-04 00:09 UTC, ashdaily requested changes

2021-04-04 00:09 UTC, ashdaily commented on frontend/src/context/CartReducer.js
> +		items.length > 0 ? items.reduce((total) => total + 1, 0) : 0;
indentation ? please fix this

2021-04-04 00:09 UTC, ashdaily commented on frontend/src/context/CartReducer.js
> +				.toFixed(2)
if there is more than 1 condition level, use `if/else` rather than `?` operator because it's more readable.

2021-04-04 00:09 UTC, ashdaily commented on frontend/src/context/WishListReducer.js
> +		});
no error handling ?

2021-04-04 00:09 UTC, ashdaily commented on frontend/src/pages/Wishlist.js
> +import { ShopContext } from "../context/ShopContext";
separate the imports, add one line between yarn packages and components. Please do this on all the files.

2021-04-04 14:29 UTC, Jerry-1947 commented on frontend/src/components/AddToCartButton.js
> +		return !!cartItems.find((item) => item.id === product.id && item.variant_id === variant.id);
Because now there is only one size for each variant product, we can easily get the size from variant ID

2021-04-04 15:02 UTC, Jerry-1947 commented on frontend/src/components/WishlistButton.js
> +		return !!wishlistItems.find((item) => item.id === product.id);
I removed the `!!` symbol

2021-04-04 15:35 UTC, Jerry-1947 commented on frontend/src/components/ProductDetailsContent.js
> +			id: data.product_variants.find((item) => item.color === color).id,
Will Create for this new issue

2021-04-06 13:30 UTC, ashdaily approved these changes

2021-04-06 13:32 UTC, merged