issue#71 wishlist changes
ashdaily/turbocommerce pull request #81
Opened 2021-04-25 20:46 UTC by Jerry-1947

2021-04-26 13:40 UTC, ashdaily requested changes

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/components/Sizes.js
> +        >
use `mb-*` `p-*` bootstrap classes for consistency. Avoid inline css as much as possible please.

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/context/WishListReducer.js
> +	}
Reminder: don't use tabs, fix this indentation.

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/components/WishlistButton.js
> +        toast.success("Product added to wishlist!");
check status code before toast and hander error as well.

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/components/WishlistButton.js
> +      toast.success("Product removed to wishlist!");
check status code before showing toast and handle error

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/components/WishlistButton.js
> +        Add to wishlist <i className="far fa-heart"></i>
there is a typo in this line, ~~far~~ ⛔ , `fa` ✅

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/context/WishListReducer.js
> +	}
fix the indentation 🤦

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/context/WishListReducer.js
> +	return { totalWishlistItems };
fix indentation

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/context/WishListReducer.js
> +			}
indentation

2021-04-26 13:40 UTC, ashdaily commented on frontend/src/context/WishListReducer.js
> +	}
indentation

2021-04-26 18:40 UTC, Jerry-1947 commented on frontend/src/components/WishlistButton.js
> +        Add to wishlist <i className="far fa-heart"></i>
This is used in font awesome 5

2021-04-28 14:41 UTC, ashdaily approved these changes

2021-04-28 14:41 UTC, merged